server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://j8b306.p.ssafy.io:8761/eureka  # http://localhost:8761/eureka #


spring:
  application:
    name: paragraph-service
  jpa:
    hibernate:
      ddl-auto:  update
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://j8b306.p.ssafy.io:3306/booklet_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: booklet
    password: qnrwjrqnrwjr!qnrfpt
  # swagger
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
